build_and_test:
  script:
    - docker run --rm -v $PWD:/override ocaml/opam2:4.07
        /override/ci-scripts/build_and_test.sh file:///override/

opam-pin_and_install:
    - docker run --rm -v $PWD:/override ocaml/opam2:4.07
        /override/ci-scripts/opam-pin_and_install.sh file:///override/