stages:
  - prepare
  - build

make opam file:
  stage: prepare
  script:
    - opam update
    - opam upgrade --yes
    - dune build override.opam
  artifacts:
    paths:
      - override.opam

.build and test: &build_and_test_def
  stage: build
  script:
    - docker run --rm --volume $PWD:/override ocaml/opam2:$ocaml_version
        /override/ci-scripts/build_and_test.sh file:///override/

opam pin and install:
  stage: build
  script:
    - docker run --rm --volume $PWD:/override ocaml/opam2:4.08
        /override/ci-scripts/opam-pin_and_install.sh file:///override/

build and test on 4.08:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.08"

build and test on 4.07:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.07"

build and test on 4.06:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.06"

build and test on 4.05:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.05"

build and test on 4.04:
  <<: *build_and_test_def
  variables:
    ocaml_version: "4.04"

snapshot:
  only:
    refs:
      - master
  script:
    - wget https://gitlab.inria.fr/tmartine/redirect/raw/master/snapshot.sh
    - chmod +x snapshot.sh
    - ./snapshot.sh
